from typing import Any, Protocol

from uall_core.schemas.common import (
    Experiment,
    PolicyVersion,
    RetrievalTelemetryEvent,
    Skill,
    VersionRecord,
)
from uall_core.schemas.events import Event, Feedback, RunEnd, RunStart
from uall_core.schemas.lesson import Lesson, MemorySearchRequest, PendingLesson


class StoragePort(Protocol):
    """Pluggable storage interface for all UALL tiers."""

    async def init(self) -> None: ...

    # Runs & events
    async def save_run_start(self, run: RunStart) -> None: ...
    async def save_run_end(self, run: RunEnd) -> None: ...
    async def save_event(self, event: Event) -> None: ...
    async def get_event(self, event_id: str) -> dict[str, Any] | None: ...
    async def save_feedback(self, feedback: Feedback) -> str: ...
    async def get_run(self, run_id: str) -> dict[str, Any] | None: ...
    async def list_runs(self) -> list[dict[str, Any]]: ...

    # Lessons & memory
    async def save_lesson(self, lesson: Lesson) -> str: ...
    async def get_lesson(self, lesson_id: str) -> Lesson | None: ...
    async def list_lessons(self, status: str = "active") -> list[Lesson]: ...
    async def update_lesson(self, lesson: Lesson) -> None: ...
    async def delete_lesson(self, lesson_id: str) -> None: ...
    async def search_lessons(self, request: MemorySearchRequest) -> list[Lesson]: ...

    # Pending promotion queue
    async def save_pending(self, pending: PendingLesson) -> str: ...
    async def get_pending(self, pending_id: str) -> PendingLesson | None: ...
    async def list_pending(self, status: str = "pending") -> list[PendingLesson]: ...
    async def update_pending(self, pending: PendingLesson) -> None: ...

    # Policies
    async def save_policy(self, policy: PolicyVersion) -> str: ...
    async def get_active_policies(self) -> list[PolicyVersion]: ...
    async def list_policy_versions(self, policy_id: str) -> list[PolicyVersion]: ...

    # Skills
    async def save_skill(self, skill: Skill) -> str: ...
    async def get_skill(self, skill_id: str) -> Skill | None: ...
    async def search_skills(self, query: str) -> list[Skill]: ...

    # Telemetry
    async def save_telemetry(self, event: RetrievalTelemetryEvent) -> str: ...
    async def list_telemetry(self, lesson_id: str | None = None) -> list[RetrievalTelemetryEvent]: ...

    # Experiments
    async def save_experiment(self, experiment: Experiment) -> str: ...
    async def get_experiment(self, experiment_id: str) -> Experiment | None: ...
    async def update_experiment(self, experiment: Experiment) -> None: ...

    # Versions (rollback)
    async def save_version(self, record: VersionRecord) -> str: ...
    async def list_versions(self, resource_type: str, resource_id: str) -> list[VersionRecord]: ...

    # Reflections
    async def save_reflection(self, data: dict[str, Any]) -> str: ...
    async def get_reflection(self, reflection_id: str) -> dict[str, Any] | None: ...

    # Metrics / analytics raw
    async def save_metrics(self, name: str, data: dict[str, Any]) -> None: ...
    async def get_metrics(self, name: str) -> dict[str, Any] | None: ...
